# Generated by Django 5.2.4 on 2025-07-25 04:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=225)),
                ('cname', models.CharField(max_length=225)),
                ('events', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('startdate', models.DateField()),
                ('enddate', models.DateTimeField()),
                ('contact', models.CharField(max_length=15)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
