# Generated by Django 5.2.4 on 2025-07-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='aname',
            new_name='ename',
        ),
    ]
