# Generated by Django 5.2.4 on 2025-07-25 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_rename_aname_event_ename'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='enddate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='startdate',
            field=models.CharField(max_length=100),
        ),
    ]
