# Generated by Django 5.2.4 on 2025-07-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_event_location_alter_event_enddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cname',
            new_name='collegeName',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='enddate',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='ename',
            new_name='eventName',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startdate',
            new_name='startDate',
        ),
    ]
